name: Build BestClient
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install pkg-config ninja-build libcurl4-openssl-dev libfreetype6-dev libnotify-dev libogg-dev libopus-dev libopusfile-dev libsdl2-dev libsqlite3-dev libavcodec-dev libavformat-dev libavutil-dev libswresample-dev libswscale-dev libx264-dev libpng-dev libglew-dev libwebsockets-dev -y
          
      - name: Setup CMake
        uses: lukka/get-cmake@latest
        
      - name: Configure and Build
        run: |
          cd BestClient-Latest-GQ
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -GNinja -DDISCORD=OFF -DVULKAN=OFF
          cmake --build .
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BestClient-Executable
          path: BestClient-Latest-GQ/build/BestClient*
