name: Build BestClient
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libcurl4-openssl-dev libsqlite3-dev libfreetype6-dev libogg-dev libopus-dev libopusfile-dev libsdl2-dev libpng-dev rustc cargo python3 python3-pip
          
      - name: Setup CMake
        uses: lukka/get-cmake@latest
        
      - name: Configure and Build
        run: |
          cd BestClient-Latest-GQ
          mkdir build
          cd build
          cmake .. -DDISCORD=OFF
          cmake --build . --config Release -j4
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BestClient-Executable
          path: BestClient-Latest-GQ/build/BestClient*
