name: Build BestClient (Windows)
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies via vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'master'
          
      - name: Setup CMake
        uses: lukka/get-cmake@latest
        
      - name: Configure and Build
        run: |
          cd BestClient-Latest-GQ
          mkdir build
          cd build
          cmake .. -DDISCORD=OFF
          cmake --build . --config Release
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BestClient-Windows
          path: BestClient-Latest-GQ/build/Release/*.exe
