name: Build BestClient
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies via vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.bat
          ./vcpkg integrate install
          ./vcpkg install curl freetype glew gtest libpng libogg openssl opus libopusenc opusfile sdl2 sqlite3 wavpack zlib
        
      - name: Setup CMake
        uses: lukka/get-cmake@latest
        
      - name: Configure and Build
        run: |
          cd BestClient-Latest-GQ
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../../vcpkg/scripts/buildsystems/vcpkg.cmake -DDISCORD=OFF
          cmake --build . --config Release
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BestClient-Executable
          path: BestClient-Latest-GQ/build/Release/*.exe
